### ISSUE TITLE
Gem fails to install under JRUBY 9.1.8.0

### ISSUE THREAD

**Issue by rebelwarrior** [k0kubun/hamlit#100]
Can't install gem under JRuby probably missing native extensions. 😢

**Comment by k0kubun** [comment]
😭 

We can having Ruby code for C ext part but I am reluctant to do that. And I don't know better solution for this yet. How do you JRuby guys solve such problems usually?

**Comment by rebelwarrior** [comment]
Usually we and by we I mean they, would code it in Java. 

I don't speak Java but I'll see if some of my co-workers will help me if you're willing to guide me on what to do. :-)

**Comment by knightq** [comment]
No chance to be solved or workarounded?

**Comment by k0kubun** [comment]
I started to implement this. That'll be solved shortly. There's no direct workaround but you can use Haml 5 for now.

**Comment by k0kubun** [comment]
Haha, I've just noticed I started to work on that a year and a half ago and it's still not done now... :)

I'll take a look at this again today.

**Comment by remofritzsche** [comment]
@k0kubun  That would be amazing, thank you. Let me know if I can be of any assistance.

**Comment by k0kubun** [comment]
Initially I was planning to implement all with Java extension, but I changed my plan to implement all with Ruby first and then migrate it to Java extension one by one. Even so, this should be already faster than Haml gem. Anyway, this issue should be ready to be closed.

**Comment by remofritzsche** [comment]
Brilliant, thank you! Version 2.9.1 does not seem to be installable under jRuby though:

```jgem install hamlit
Building native extensions. This could take a while...
ERROR:  Error installing hamlit:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/hamlit-2.9.1/ext/hamlit
/usr/local/Cellar/jruby/9.2.0.0/libexec/bin/jruby -r ./siteconf20181101-99342-1vw25i6.rb extconf.rb
creating Makefile

current directory: /usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/hamlit-2.9.1/ext/hamlit
make "DESTDIR=" clean

current directory: /usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/hamlit-2.9.1/ext/hamlit
make "DESTDIR="
make: *** No rule to make target `/usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/include/ruby/ruby.h', needed by `hamlit.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/hamlit-2.9.1 for inspection.
Results logged to /usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.0/hamlit-2.9.1/gem_make.out
```

`gem_make.out`:

```
current directory: /usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/hamlit-2.9.1/ext/hamlit
/usr/local/Cellar/jruby/9.2.0.0/libexec/bin/jruby -r ./siteconf20181101-99342-1vw25i6.rb extconf.rb
creating Makefile

current directory: /usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/hamlit-2.9.1/ext/hamlit
make "DESTDIR=" clean

current directory: /usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/gems/shared/gems/hamlit-2.9.1/ext/hamlit
make "DESTDIR="
make: *** No rule to make target `/usr/local/Cellar/jruby/9.2.0.0/libexec/lib/ruby/include/ruby/ruby.h', needed by `hamlit.o'.  Stop.

make failed, exit code 2
```

**Comment by k0kubun** [comment]
Uh oh. Thanks to report that. Let me take another look...

**Comment by remofritzsche** [comment]
Brilliant, now it works like a charm! Thanks again @k0kubun 🥇

**Comment by rebelwarrior** [comment]
Tested it on mine and it worked as well!
