### ISSUE TITLE
Nominate @k0kubun to be Ruby Hero

### ISSUE THREAD

**Issue by WaKeMaTTa** [k0kubun/hamlit#102]
@k0kubun you are awesome. That is way last year i did nominate you to be come [*Ruby Hero*](https://rubyheroes.com/)

This year i will nominate you again, and i invite the other to join the cause. :smile: 

Stay awesome! :tada:

**Comment by k0kubun** [comment]
Oh, thank you! :smile: 
I'll continue to stay good for community.

**Comment by WaKeMaTTa** [comment]
Sorry @k0kubun , RubyHeros is :skull: .
