### ISSUE TITLE
Add erubi to the benchmark

### ISSUE THREAD

**Issue by WaKeMaTTa** [k0kubun/hamlit#106]
Hello @k0kubun 

Can we add [erubi](https://github.com/jeremyevans/erubi) in to the benchmark and the [graphic](https://camo.githubusercontent.com/00821c974c56d7da97806eff181a55af417009c7/68747470733a2f2f692e6779617a6f2e636f6d2f61633965623931306337323631636330313831626437343237633836306437392e706e67)?

Thanks.

**Comment by k0kubun** [comment]
Done. Because I optimized both Haml https://github.com/haml/haml/pull/904 and Erubi https://github.com/jeremyevans/erubi/pull/4, Hamlit became relatively slower. :laughing:
