### ISSUE TITLE
Exec HAMLIT command into rails

### ISSUE THREAD

**Issue by francesco-loreti** [k0kubun/hamlit#107]
HI!
Is it possible to implement the possibility to execute the HAMLIT commands into rails application? Because, for example, I can render a template from command line out of rails program("hamlit rendere filename.html.haml") but not inside application or into rails console.

Thanks

**Comment by k0kubun** [comment]
I couldn't understand you intention. Could you provide example use case with following things?

- Haml template source code
- Command to execute
- expected stdout, stderr and exit status

<hr>

For example,

### Haml template source code
example.haml:

```haml
%foo
```

### Command to execute
```
$ hamlit render example.haml
```

### stdout, stderr and exit status
#### stdout
```html
<div class='foo'></div>
```

#### stderr
```
```

#### exit status
0

<hr>

And as you may know, example above is already implemented. So I want some other *Rails-specific* use case that can't be done with it.

Thanks.

**Comment by francesco-loreti** [comment]
If I use ERB I can user ERB.new for render inside my application an erb file. More or less as http://blog.revathskumar.com/2014/10/ruby-rendering-erb-template.html

In HAMLIT is it possible?

**Comment by k0kubun** [comment]
Possible. Sorry for poor documentation.

```rb
foo = "hello world"
ERB.new("<%= foo %>").result(binding) #=> "hello world"
```

is the same as:

```rb
foo = "hello world"
eval(Hamlit::Engine.new.call("= foo"), binding) #=> "hello world"
```

and:

```rb
Hamlit::Template.new { "= foo" }.render(nil, { foo: "hello world" })
```
