### ISSUE TITLE
How to know if you are using hamlit

### ISSUE THREAD

**Issue by WaKeMaTTa** [k0kubun/hamlit#108]
Hello,

How i can know if im using `hamlit` or `haml` in my application :question: 

In my `Gemfile` i have 

- `gem 'hamlit'` 

but in my `Gemfile.lock` i have 

- `hamlit (2.2.1)`
- `haml (4.0.7)`

**Comment by k0kubun** [comment]
## In Rails
```rb
ActionView::Template.handler_for_extension("haml")
=> #<Hamlit::RailsTemplate:0x005593caad2150>
```

## In Sinatra, or any Tilt environment
```rb
Tilt["haml"]
=> Hamlit::Template
```

## Or in all environments, you can try to render incompatibility
### input
```haml
%div{ foo: false }
```

### output in Haml
```html
<div></div>
```

### output in Hamlit
```html
<div foo=''></div>
```
