### ISSUE TITLE
Option to generate compile/parse/... output from cli *without* ANSI color codes

### ISSUE THREAD

**Issue by kikonen** [k0kubun/hamlit#111]
Having ANSI color codes in output makes life more difficult when intension is to open file in text editor (which by itself handles proper color highlighting based into file type).

So far I noticed only workaround to be editing "cli.rb" and disabling pry highlighting there.

Not really big deal since my workaround works fine enough.

Side note: Personally I don't care much about highlighting either in console (due to readability; yellow or such fg in "white/light yellow" terminal bg color is not very good for reading :) )

**Comment by k0kubun** [comment]
Actually it was evil to switch behavior with pry existence. So I changed coloring to opt-in. Released as v2.8.2.

**Comment by k0kubun** [comment]
Ah... forgot about parse...

**Comment by k0kubun** [comment]
Fixed them too in v2.8.3.

**Comment by kikonen** [comment]
nice :)
