### ISSUE TITLE
Register a custom filter?

### ISSUE THREAD

**Issue by swrobel** [k0kubun/hamlit#114]
How do I register a custom filter, say [babel-transpiler](https://github.com/kgrz/sinatra-haml-es6/blob/master/app.rb) for es6?

**Comment by k0kubun** [comment]
Like this:

```rb
module Hamlit
  class Filters
    class Es6 < TiltBase
      def compile(node)
        # branch with `@format` here if you want
        compile_html(node)
      end

      private

      def compile_html(node)
        temple = [:multi]
        temple << [:static, "<script>\n"]
        temple << compile_with_tilt(node, 'es6', indent_width: 2)
        temple << [:static, "\n</script>"]
        temple
      end
    end
    register :es6, Es6 # <-- this part
  end
end
```

Unfortunately Hamlit doesn't have the compatible interface with `register_tilt_filter` (it generates a filter for Tilt and inherits existing one if necessary, and it depends on Haml's internal). 

I hope the above code works for your use case.

**Comment by swrobel** [comment]
Thank you so much for the quick reply. That worked perfectly. 😁
