### ISSUE TITLE
Markdown not working

### ISSUE THREAD

**Issue by doutatsu** [k0kubun/hamlit#120]
Sorry if this is something obvious, but I've been trying to use `:markdown` syntax in my haml files. As I understand, by default it uses `redcarpet` for that, but when I try to render the page, I get an error `cannot load such file -- redcarpet`. Does it not come with `tilt`? Do I have to either manually initialize it or use a gem for that?

**Comment by k0kubun** [comment]
You need to install redcarpet.gem. It's not added as runtime dependency because using markdown is optional. It should happen even if it's built with Tilt because tilt.gem doesn't require redcarpet.gem too.
