### ISSUE TITLE
question: yield in yield

### ISSUE THREAD

**Issue by dux** [k0kubun/hamlit#126]
for a given template part inside haml template

```
    = my_func do
      %h1 Title
      = yield

```

I do not know how to pass data to the yield inside the block.

thx

**Comment by WaKeMaTTa** [comment]
Maybe this will help you https://stackoverflow.com/questions/14373057/what-is-the-difference-between-render-and-yield-in-rails#answer-14377685

**Comment by k0kubun** [comment]
The question itself could depend on what block could be passed to the code generated by Hamlit. In pure-Ruby theory, a block passed to a method can be yielded by `yield` inside a child block. So the `yield` in the issue description would yield a block passed to the method which was defined by the code generated from the template by Hamlit.

If you're using Rails, it's the matter of `ActionView::Template` and some hash that can be modified by `content_for` would be given. The comment from @WaKeMaTTa may help. In the Hamlit's built-in interface `Hamlit::Template#render` which is actually defined by Tilt and can be used for Sinatra, it takes a block and that would be called by the `yield`.

Anyway, at least Hamlit has an interface for it and this is not an issue. So let me close this.
