### ISSUE TITLE
Coding style for project

### ISSUE THREAD

**Issue by yb66** [k0kubun/hamlit#134]
Afternoon,

Following on from [your comments about coding style](https://github.com/k0kubun/hamlit/pull/133#issuecomment-456362809), would it be an idea to start a section in the README, or perhaps add Rubocop, to help avoid any problems with future contributions? I'm happy to start it so you can fill in more details when convenient.

Regards,
iain

**Comment by k0kubun** [comment]
Unfortunately I don't have enough time for clarifying my own coding style for now. I'm so sorry but I need to ask you to read the current implementation and follow it. Thank you.
