### ISSUE TITLE
whcih pandoc or which pandoc inside test

### ISSUE THREAD

**Issue by pironim** [k0kubun/hamlit#135]
https://github.com/k0kubun/hamlit/blob/master/test/hamlit/filters/markdown_test.rb#L6
I can be wrong but this line looks like typo. `whcih pandoc` ?

**Comment by pironim** [comment]
actually there two places with the same code.
https://github.com/WaKeMaTTa/hamlit/blob/5528bf9abc432bbf506d447048c6338e0a5fc777/test/hamlit/filters/markdown_test.rb#L23

**Comment by pironim** [comment]
you still have whcih on line 23

**Comment by k0kubun** [comment]
thanks, fixed again
