### ISSUE TITLE
TruffleRuby support

### ISSUE THREAD

**Issue by deepj** [k0kubun/hamlit#144]
Currently it's not possible to compile Hamlit under TruffleRuby due to this limitation https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md#value-is-a-pointer

Here is an open issue https://github.com/oracle/truffleruby/issues/1600

Is it possible to support TruffleRuby?

**Comment by k0kubun** [comment]
Implemented. I commented details in https://github.com/oracle/truffleruby/issues/1600#issuecomment-529179185 and https://github.com/oracle/truffleruby/issues/1747.
