### ISSUE TITLE
hamlit v2.10.0 breaks hamlit-block v0.6.0

### ISSUE THREAD

**Issue by flash-gordon** [k0kubun/hamlit#149]
👋 This [change](https://github.com/k0kubun/hamlit/commit/e00f78f0fdcf283a40a00bb2787f66c5fce5208b) in hamlit made. `Hamlit::StringSplitter` a `Module`, not a `Class` 
hamlit-block [passes](https://github.com/hamlit/hamlit-block/blob/792d89525242627d00957e431be8e597e40b2145/lib/hamlit/block/engine.rb#L23) `Hamlit::StringSplitter` to a [method](https://github.com/judofyr/temple/blob/eff68901cbc75441ca5fee835f30b533ebbd8560/lib/temple/mixins/engine_dsl.rb#L107-L109) of the temple gem.  It checks if the argument is a `Class`, this check used to pass. Now an `ArgumentError` is thrown.

I'm not sure what's the best course of action here, making `StringSplitter` a class is the simplest thing to do, though.

I discovered this breakage during routine tasks in dry-view /cc @timriley

**Comment by k0kubun** [comment]
You're absolutely right. That's a great explanation.

I released hamlit-block v0.7.0 to just fix the immediate issue. I think we could loosen the tight coupling between them by inheriting how hamlit assembles filters, but at this moment that should make it work.

**Comment by flash-gordon** [comment]
Thank you, I can confirm it works ❤️
