### ISSUE TITLE
Show basic console render example in README/similar

### ISSUE THREAD

**Issue by 0xdevalias** [k0kubun/hamlit#151]
I had to dig a bunch to actually find how to do this, but found my snippet in:
- https://github.com/k0kubun/hamlit/blob/master/test/test_helper.rb#L43-L47

```ruby
def render_hamlit(haml, options = {})
  options = options.dup
  locals  = options.delete(:locals) || {}
  Hamlit::Template.new(options) { haml }.render(Object.new, locals)
end
```

So a super minimal example would be:

```ruby
Hamlit::Template.new { "%strong Yay for HAML!" }.render
```

Even including this in https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md would be good.

It seemed a lot easier to find the documentation for the equivalent haml API (linked from the README):

- https://github.com/haml/haml#formatting
  - > Haml provides far more tools than those presented here. Check out the reference documentation for full details.
- http://haml.info/docs/yardoc/file.REFERENCE.html#ruby-module

> You can then use it by including the “haml” gem in Ruby code, and using Haml::Engine like so:
> ```ruby
> engine = Haml::Engine.new("%p Haml code!")
> engine.render #=> "<p>Haml code!</p>\n"
> ```

It seems hamlit doesn't support the same sort of API (which was my initial assumption/attempt):

```
[38] pry(main)> engine = Hamlit::Engine.new("%strong Yay for HAML!")
NoMethodError: undefined method `to_hash' for "%strong Yay for HAML!":String
Did you mean?  to_s
from /Users/devalias/dev/foo/vendor/bundle/ruby/2.4.0/gems/temple-0.8.2/lib/temple/map.rb:87:in `validate_map!'
```

**Comment by k0kubun** [comment]
I adopted your idea in https://github.com/k0kubun/hamlit/commit/8783cef8ad11a572c688430d5b7319721052bdcc.

`Hamlit::Engine` implements haml's `Haml::TempleEngine` which can just generate a compiled Ruby code. `Hamlit::Template` implements tilt's `Tilt::HamlTemplate`. 

I think Tilt is a good standard of rendering interface, and you can use it for your Ruby module usage. So I'm not going to implement Haml's original interface `Haml::Engine` in Hamlit.

**Comment by 0xdevalias** [comment]
That works for me :) Thanks!
