### ISSUE TITLE
Feature request :) - for / else

### ISSUE THREAD

**Issue by dux** [k0kubun/hamlit#159]
The same it is implemented in Svelte https://github.com/sveltejs/svelte/issues/90

It would be nice, if we would be able to write

```
- for el in @model.children
  %p= el.name
- else
 .danger List is empty
```

and not as now

```
- children = @model.children
- if children.first
  - for el in children
    %p= el.name
- else
 .danger List is empty
```

I suggest not to play smart, just if for produces `blank? - true`, use `else` block.

Added to https://github.com/haml/haml/issues/1037 as well.

**Comment by WaKeMaTTa** [comment]
I think feature requested they need to be approved first in https://github.com/haml/haml

**Comment by dux** [comment]
ok, but why? This does not brake compatibility.

**Comment by WaKeMaTTa** [comment]
Because Hamlit only implements the features of haml.

Le lun. 27 juil. 2020 à 12:57, Dino Reić <notifications@github.com> a
écrit :

**Comment by k0kubun** [comment]
@WaKeMaTTa is right. One of the reasons is that Hamlit shares the same parser as Haml, and not using the exact same parser increases maintenance cost of Hamlit. So at least syntax-level features like this should be proposed and implemented in Haml to avoid diverging the parser part.

Thanks for filing https://github.com/haml/haml/issues/1037! Please feel free to reopen this issue once it's merged.
