### ISSUE TITLE
Class name ordering

### ISSUE THREAD

**Issue by aliismayilov** [k0kubun/hamlit#161]
Since https://github.com/haml/haml/issues/306 is resolved and [haml version 5.2 release](https://github.com/haml/haml/blob/main/CHANGELOG.md#52), the tests are failing on the master branch, mostly because of class sorting.

**Comment by k0kubun** [comment]
Good catch, I didn't think it'd automatically fail on hamlit. I will take a look.

**Comment by k0kubun** [comment]
OK, fixed and released it as v2.12.0.
