### ISSUE TITLE
What happened to "ugly" option?

### ISSUE THREAD

**Issue by kikonen** [k0kubun/hamlit#164]
Seeing now this with hamlit 2.13.0

```
 #<ActionView::Template::Error: undefined method `ugly=' for #<Hamlit::HamlOptions:0x00007fbc2ceb0178>
```

What happened to that option?

**Comment by k0kubun** [comment]
Sorry for the trouble. I guess it's about not 2.3.0 but 2.13.0, right? 

I can understand it's related to the change at v2.13.0, but technically Hamlit (and Haml 5) has not supported ugly option. Do you specifically specify `ugly` in your Rails initializer, or does that happen with default configurations? I'd appreciate a repository which reproduces the issue if you can provide it.

**Comment by kikonen** [comment]
It was used explicitly to produce more compact html output with very large tables

**Comment by k0kubun** [comment]
I see. That had been a valid technique until Haml 4, but both Haml 5 and Hamlit produce the "more compact html output" without specifying `ugly` option. The option was accidentally accepted for internal implementation even while it doesn't configure anything. Please just remove the specification.

**Comment by kikonen** [comment]
Seemingly http://chriseppstein.github.io/blog/2010/02/08/haml-sucks-for-content/ is reason why it was used (see "Performance" chapter).
