### ISSUE TITLE
Support of "annotate_template_file_names" or equivalent 

### ISSUE THREAD

**Issue by kirin121** [k0kubun/hamlit#180]
Recently in Rails 6.1 was introduced option to annotate rendering of templates with some debug comments. 
Internally such behavior is handled by `actionview/lib/action_view/template/handlers/erb/erubi.rb `:
```ruby

if ActionView::Base.annotate_template_file_names
  properties[:preamble]   = "@output_buffer.safe_append='<!-- BEGIN #{properties[:short_identifier]} -->\n';"
  properties[:postamble]  = "@output_buffer.safe_append='<!-- END #{properties[:short_identifier]} -->\n';@output_buffer.to_s"
else
  properties[:preamble]   = ""
  properties[:postamble]  = "@output_buffer.to_s"
end

```
https://github.com/rails/rails/pull/38848
That's very useful developer-time-saving feature, especially on projects with complex layouts. 

Is there any way to enable behavior like this in `hamlit`?
(register callback, additional prefix handler, etc)

**Comment by k0kubun** [comment]
Done. Please try v2.14.5.

**Comment by kirin121** [comment]
@k0kubun , just updated gem. Works perfect.
That's awesome!
Thank you very much. 🎂
