### ISSUE TITLE
coffee-script gem is deprecated

### ISSUE THREAD

**Issue by pravi** [k0kubun/hamlit#190]
see https://github.com/rails/ruby-coffee-script/issues/22 and will never be updated to support coffeescript 2.

In debian we already moved to coffeescript 2 and we are not able to run the tests any more.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013499

Can you remove the usage of coffeescript?

**Comment by pravi** [comment]
https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b and https://github.com/rails/jsbundling-rails seems to be recommended by rails developers now

**Comment by k0kubun** [comment]
Fixed in v3.0.1.

**Comment by pravi** [comment]
@k0kubun thanks!
