### ISSUE TITLE
Question: with HAML 6.0, what is the future of Hamlit?

### ISSUE THREAD

**Issue by tagliala** [k0kubun/hamlit#193]
Hi!

Thanks for your efforts to bring hamlit into HAML

Should projects using hamlit migrate to HAML 6.0?

**Comment by WaKeMaTTa** [comment]
I made the same question [here](https://twitter.com/k0kubun/status/1561074834104168448).

His answer was:

> You can, but not really needed for now. If I were to choose only one to maintain in the future, I would choose haml.gem, but for now I don't intend to stop maintaining Hamlit. Even when you need to do it, switching from Hamlit to Haml 6 should be pretty easy.

**Comment by tagliala** [comment]
Thanks!
