### ISSUE TITLE
Performance degradation when going from haml 5.2 -> haml 6 (hamlit) on ruby 2.6.8 and Apple M2?

### ISSUE THREAD

**Issue by jontebol** [k0kubun/hamlit#194]
Don't know if this is an issue with my local env or what, but I tried upgrading to haml 6 to get a nice performance bump, but instead things got a little bit slower. Not much, but after having refreshed a bunch of pages in our app a bunch of times, it seems something like 10% slower. I checked the architecture of `haml.o` and `hescape.o` and they where both `arm64` to rule out Rosetta kicking in to emulate or something like that.

I tried getting the [benchmarks](https://github.com/k0kubun/hamlit/blob/master/benchmark/slim/run-benchmarks.rb) running to verify but probably couldn't get the dependencies right because temple complained about wrong number of arguments passed to `Haml::Engine.new(@haml_code, format: :html5, escape_html: true)`, even though I tried with the same versions of haml, slim etc that are specified in the readme.

Maybe this is just locally and hamlit would be faster in production (on linux and x86), but I would sort of like to verify that it's faster for our app before making the switch.

**Comment by k0kubun** [comment]
If you're using haml.gem, can you file this at https://github.com/haml/haml? Haml 6 and Hamlit are different gems.

**Comment by k0kubun** [comment]
Also, try running the Haml repository's benchmark https://github.com/haml/haml/blob/main/benchmark/slim/run-benchmarks.rb instead of this repository's when you file it there. I'll update Hamlit's one later but the benchmark script is currently outdated.

**Comment by k0kubun** [comment]
moved to https://github.com/haml/haml/issues/1099
