### ISSUE TITLE
Sinatra does not work?

### ISSUE THREAD

**Issue by resistorsoftware** [k0kubun/hamlit#25]
* Exchanged *hamlit* for *haml* in my bundle
* pushed to Heroku, refreshed. Saw RAW html where HTML should have been rendered?

eg route:

     get 'fizzy' do
          haml  :junk, layout: :layout_internal
     end

So why does this fail? My views/ contains a file named *junk.haml* that contains perfect HAML

**Comment by k0kubun** [comment]
Thank you for reporting an issue. Sorry for taking your time by my mistake.

Can I see your repository or a minimum reproductive one?

**Comment by resistorsoftware** [comment]
I gave you a repo. Not sure how that will help. All I did was bundle 'hamlit' for haml and run it. Is there something else I need to do?

**Comment by k0kubun** [comment]
Thanks. I could find out what's wrong easily.

Your repository was using haml without html escaping. Haml gem disables it by default.
For some reason, I decided to enable it by default in hamlit gem in https://github.com/k0kubun/hamlit/pull/18 and also dropped the option itself.

But your application does not work well with html escaping. I resurrected `escape_html` option for you in hamlit v1.3.0.
Could you try using hamlit v1.3.0 and adding `set :haml, { escape_html: false }`?

**Comment by resistorsoftware** [comment]
Excellent! Worked perfect! Thank you!

**Comment by k0kubun** [comment]
:)
