### ISSUE TITLE
String comparison with nil

### ISSUE THREAD

**Issue by jeffblake** [k0kubun/hamlit#31]
%span.pull-right{style: 'font-size:1.1em;font-weight:bold'}

That blows up the compiler.

**Comment by k0kubun** [comment]
Thank you for reporting an issue. But I couldn't reproduce your problem with your code. Could you provide more information?

```haml
$ gem list | grep hamlit
hamlit (1.6.7)
$ cat a.haml
%span.pull-right{style: 'font-size:1.1em;font-weight:bold'}
$ hamlit a.haml
<span class='pull-right' style='font-size:1.1em;font-weight:bold'></span>
```

**Comment by jeffblake** [comment]
I ended up removing that code some time ago... sorry that I didn't get back to you. Going to close this

**Comment by k0kubun** [comment]
No problem. Thank you for your response and I'm sorry for taking your time.
