### ISSUE TITLE
No haml_tag

### ISSUE THREAD

**Issue by j4rs** [k0kubun/hamlit#33]
There's no haml_tag method :(

**Comment by k0kubun** [comment]
Thank you for reporting an issue. Currently the support of `Haml::Helpers` is incomplete. But I'll implement it later because you use it :)

By the way, why do you use haml_tag? Because haml_tag is dinamically called, hamlit can't analyze it statically and give up to optimize. So the rendering speed will not be optimized. (Of course other overheads will be optimized comparing to haml.)

**Comment by j4rs** [comment]
Hey,
I want to give your gem a try - HAML has poor performance, my New Relic reports .haml taking 600ms to render, that's not unacceptable.

So, here's one scenario where my system uses **haml_tag**, maybe you find a workaround and there's no need to implement it:

```
  def stripe_payment_button(job, amount, description, email = nil)
    capture_haml do
      haml_tag 'script',
        type: 'text/javascript',
        class: 'stripe-button',
        src: 'https://checkout.stripe.com/checkout.js',
        'data-key'=> Rails.configuration.stripe[:publishable_key],
        'data-amount' => amount,
        'data-name'=> "#{job.title}",
        'data-description' => description,
        'data-image' => '/assets/icon.png',
        'data-panel-label' => t('payment.pay.label'),
        'data-allow-remember-me' => "true",
        'data-email' => _email
    end
  end
```

Then I reuse that method in different views and context.

Thanks.

**Comment by j4rs** [comment]
Anyway, I am eager to test your gem, so I'll get rid - for now - of **haml_tag** to see how my system performs, will let you know.

**Comment by k0kubun** [comment]
> I want to give your gem a try - HAML has poor performance, my New Relic reports .haml taking 600ms to render, that's not unacceptable.
> Anyway, I am eager to test your gem, so I'll get rid - for now - of haml_tag to see how my system performs, will let you know.

Wow. Thank you for trying this gem!

While I want to support it for easy migration, I could think of one workaround for now.

```haml
-# shared/stripe_payment_button.html.haml
%script{ type: 'text/javascript',
        class: 'stripe-button',
        src: 'https://checkout.stripe.com/checkout.js',
        'data-key'=> Rails.configuration.stripe[:publishable_key],
        'data-amount' => amount,
        'data-name'=> "#{job.title}",
        'data-description' => description,
        'data-image' => '/assets/icon.png',
        'data-panel-label' => t('payment.pay.label'),
        'data-allow-remember-me' => "true",
        'data-email' => _email }
```

```rb
def stripe_payment_button(job, amount, description, email = nil)
  render 'shared/stripe_payment_button', job: job, amount: amount, description: description, email: email
end
```

**Comment by k0kubun** [comment]
Because the implementation of [haml_tag](https://github.com/haml/haml/blob/c89da381a055587fa212881f9fddd2ab3c1224ca/lib/haml/helpers.rb#L489-L551) strongly depends on haml internal, it costs much to introduce. Sorry.

**Comment by j4rs** [comment]
Yeah, I am substituting my code to use partials instead, will let you know how your gem is going, you can close this issue :), thanks.

**Comment by Prizrack13** [comment]
I think it is more easier to use content_tag.
Also I refactor your method. 

```ruby
def stripe_payment_button(job, amount, description, email = nil)
  content_tag :script, '',
    type: 'text/javascript',
    class: 'stripe-button',
    src: 'https://checkout.stripe.com/checkout.js',
    data: {
      key: Rails.configuration.stripe[:publishable_key],
      amount: amount,
      name: job.title.to_s,
      description: description,
      image: image_path('/assets/icon.png'),
      panel_label: t('payment.pay.label'),
      allow_remember_me: 'true',
      email: _email
    }
end
```
