### ISSUE TITLE
Less whitespace than HAML

### ISSUE THREAD

**Issue by Carpetsmoker** [k0kubun/hamlit#36]
The `hamltit` gem seems to render less whitespace than the haml Gem.

haml:

				<div class='menu-left'>
				  <a class="btn btn-buzz-branded " href="/tickets"><i class="fa fa-inbox"></i>
				  Inbox
				  </a>
				  <a class="btn btn-buzz-branded " href="/tickets/archive"><i class="fa fa-archive"></i>
				  Archief
				  </a>
				  <a class="btn btn-buzz-branded " href="/tickets/new"><i class="fa fa-ticket"></i>
				  Maak een nieuwe ticket
				  </a>
				</div>

hamlit:

	<div class='menu-left'>
	<a class="btn btn-buzz-branded " href="/tickets"><i class="fa fa-inbox"></i>
	Inbox
	</a><a class="btn btn-buzz-branded " href="/tickets/archive"><i class="fa fa-archive"></i>
	Archief
	</a><a class="btn btn-buzz-branded " href="/tickets/new"><i class="fa fa-ticket"></i>
	Maak een nieuwe ticket
	</a></div>

Which has the result:

![spaces](https://cloud.githubusercontent.com/assets/1032692/9108133/607a8eba-3c2c-11e5-9612-1b8adb028ea6.png)

I consider the *lack* of whitespace to be better for a number of reasons, but unfortunately the application doesn't work well with this, and it's not quite "haml-compatible"...

**Comment by k0kubun** [comment]
Thank you for trying Hamlit and reporting an issue!

Is it an output of production environment?

In README, I wrote:

> Hamlit behaves the same as Haml (ugly and escape_html mode only, which is used on production).

"Ugly mode" is a mode of Haml, which does not generate indentation to render faster. I think the html you provided is indented and I guess it is "pretty mode" of Haml.
And Hamlit does **not** support indented "pretty mode" because it generates a different output from production environment. It's very confusing.

So could you provide more information? The input of haml, RAILS_ENV or RACK_ENV, the version of Haml, Hamlit and Ruby. Thanks for your help.

**Comment by Carpetsmoker** [comment]
Thanks :-)

This is my development (rails) environment, testing out `hamlit`. We haven't quite finished this application, so there's no production environment (yet), but I've looked at some other (rails) projects where I use the `haml` gem and they indeed strip whitespace in production :-/

I did look at [the HAML documentation here](http://haml.info/docs/yardoc/file.REFERENCE.html) before I reported this issue, but this behaviour isn't mentioned there, only [in some obscure page here](http://haml.info/docs/yardoc/Haml/Options.html#ugly-instance_method) it seems. I agree that this behaviour is silly.

Perhaps the `hamlit` README section can be expanded a little bit to make this difference clearer (see below).

--------

### Passing haml-spec

[haml/haml-spec](https://github.com/haml/haml-spec) is a basic suite of tests for Haml interpreters.
For all test cases in haml-spec, Hamlit behaves the same as Haml (ugly and escape\_html mode only, which is used on production).

Hamlit is used on [githubranking.com](http://githubranking.com/).

#### Incompatabilities

- [Ugly mode](http://haml.info/docs/yardoc/Haml/Options.html#ugly-instance_method) is always `true`, this means that `hamlit` will never add extra whitespace.

  Example:

		$ cat test.haml
		.hello
		  .world
			Test

		$ haml test.haml
		<div class='hello'>
		  <div class='world'>
			Test
		  </div>
		</div>

		$ hamlit test.haml
		<div class='hello'>
		<div class='world'>
		Test
		</div>
		</div>

Note that on *production* environments the `haml` output is the same as the `hamlit` output


- [Escape\_html](http://haml.info/docs/yardoc/Haml/Options.html#escape_html-instance_method) is always `true`, this means that `=` will always escape HTML.

  Example:

		$ cat test.haml
		= '<a>'
		&= '<a>'

		$ haml test.haml
		<a>
		&lt;a&gt;

		$ hamlit test.haml
		&lt;a&gt;
		&lt;a&gt;

**Comment by k0kubun** [comment]
I'm relieved to hear that :)  Thank you for your understanding.

Your proposal looks good. If you are ok, could you open a pull request?
(Of course I can do it myself if you are busy.)

**Comment by k0kubun** [comment]
Documented about pretty mode https://github.com/k0kubun/hamlit/blob/v2.0.1/REFERENCE.md#no-pretty-mode and other incompatibilities in https://github.com/k0kubun/hamlit/pull/43.
