### ISSUE TITLE
Support the haml -r flag

### ISSUE THREAD

**Issue by jhurliman** [k0kubun/hamlit#37]
I want to try converting our codebase from haml to hamlit but we're currently using the pattern `haml -r ./haml-includes.rb ...` to include common variable definitions.

**Comment by k0kubun** [comment]
Thank you for trying hamlit!

I didn't know the `haml -r` feature. So I can't imagine what is the use case and how I should implement it. How do you use `haml -r`? Aren't you building web apps? I guess you're developing background batches or CLI tools.

Anyway, I have will to support the feature.

**Comment by k0kubun** [comment]
Released as v2.1.0. :gem:
