### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by greyblake** [k0kubun/hamlit#38]
I did some measures with [RailsPanel]((https://chrome.google.com/webstore/detail/railspanel/gjpfobpafnhjhbajcjgccbbdofdckggg). A page that takes ~1 sec to be rendered with regular `haml`, takes ~6-8 secs with `hamlit` in development.

Is it expected result? Is it possible to tweak something to make it faster (I expected it to be faster than `haml`).

Thanks!

**Comment by k0kubun** [comment]
I guess there is one possible reason of the problem. Because Hamlit is not optimized for compilation, the total rendering time (compilation of template + rendering) is relatively slow on development. Does it happen on production too?
Current compilation performance is not so good. I think improving the time of compilation keeping the rendering performance is possible and I have will to do it later.

By the way, could you provide more information to reproduce your environment? 
For example, code of a template you're rendering, Ruby version, Hamlit version or Rails version.

Thank you for your cooperation!

**Comment by greyblake** [comment]
Thanks for a such quick response!
Ok, it makes sense. I haven't tried it in production. 

I can't provide the tempate (because I've tried it against commercial application), but the environment is the following:
* ruby 2.1.5p273
* rails-4.2.3
* hamlit 1.7.2

Thanks! I wan't to give it a try with my small pet project)

**Comment by greyblake** [comment]
I guess to optimize it for compilation we can to dive into https://github.com/judofyr/temple . Right?

**Comment by k0kubun** [comment]
> I can't provide the tempate (because I've tried it against commercial application)

That's reasonable. Thank you for trying Hamlit for your commercial application.

> I can't provide the tempate (because I've tried it against commercial application), but the environment is the following:

Thanks!

> I guess to optimize it for compilation we can to dive into https://github.com/judofyr/temple . Right?

While the performance optimized by temple and compilation time is trade-off, I recognize the current bottleneck of compilation is in Hamlit's code.

If you want to compare compilation time of Haml and Hamlit, you can try following code.

```rb
require 'haml'
require 'hamlit'

code = File.read('path/to/template.haml')

start = Time.now
Hamlit::Engine.new.call(code)
puts "Hamlit: #{Time.now - start}s"

start = Time.now
Haml::Engine.new(code, format: :html5, escape_html: true).compiler.precompiled_with_ambles({})
puts "Haml: #{Time.now - start}s"
```

I recommend you to check both of your internal template and outer layout.
In fact, Haml's compilation is fast. 
(But rendering on production is too slow. Again, it's trade-off. But Hamlit has possibility to optimize it.)

**Comment by k0kubun** [comment]
By the way, if you want to know where is the slow part and dive into the place, you can profile the code with https://github.com/tmm1/rblineprof.

```rb
require 'lineprof'
require 'hamlit'

Lineprof.profile do
  Hamlit::Engine.new.call(<<-HAML)
!!! html

%html
  %head
    %title Simple Benchmark
  %body
    %h1= header
    - unless item.empty?
      %ul
        - for i in item
          - if i[:current]
            %li
              %strong= i[:name]
          - else
            %li
              %a{:href => i[:url]}= i[:name]
    - else
      %p The list is empty.
  HAML
end
```

And the result is here: https://gist.github.com/k0kubun/5534d5e4e6cceb570510

**Comment by k0kubun** [comment]
Compilation became faster in https://github.com/k0kubun/hamlit/pull/43.

```
  haml v5.0.0.beta.2:      297.5 i/s (3.361ms)
      hamlit2 v2.0.1:      152.6 i/s (6.551ms) - 1.95x slower
         faml v0.7.0:      139.4 i/s (7.173ms) - 2.13x slower
      hamlit1 v1.7.2:       78.0 i/s (12.827ms) - 3.82x slower
```

https://travis-ci.org/k0kubun/hamlit/jobs/93928562

**Comment by greyblake** [comment]
Cool! Thanks! :+1:
