### ISSUE TITLE
Object reference error

### ISSUE THREAD

**Issue by gmile** [k0kubun/hamlit#39]
While trying to quickly migrate our production app to hamlit, I've spotted some tests failing with errors similar to this:

```
ActionView::Template::Error (Illegal nesting: content can't be both given on the same line as %tr and nested within it.):
    1: - decorator =  ReturnDecorator.new(self, return_record)
    2: %tr[return_record]
    3:   %td#auth_id= return_record.auth_id
    4:   %td#state= decorator.state
    5:   %td#customer
    6:     - if current_user.vendor?
  app/views/returns/_return_record.haml:3:in `_app_views_returns__return_record_haml__1226260404814508471_70111479409320'
```

It looks like there's no `[object_reference]` method in hamlit?

How do I port the function to make and hamlit aware of it?

**Comment by k0kubun** [comment]
OK, it's incompatibility and I'll implement it later.

For now, you can try following code:

```haml
- decorator =  ReturnDecorator.new(self, return_record)
  %tr{ id: dom_id(decorator) }
    %td#auth_id= return_record.auth_id
    %td#state= decorator.state
    %td#customer
      - if current_user.vendor?
```

**Comment by gmile** [comment]
Thanks @k0kubun, this is what we ended up doing

**Comment by k0kubun** [comment]
Object reference is supported in https://github.com/k0kubun/hamlit/pull/43. (with some tiny incompatibilities, though. I'll fix it later.)
