### ISSUE TITLE
Counterintuitive illegal nesting issue

### ISSUE THREAD

**Issue by gmile** [k0kubun/hamlit#40]
Stumbled upon another error:
```
ActionView::Template::Error (Illegal nesting: nesting within plain text is illegal.):
    1: %ul.nav.nav-list
    2:
    3:   %li
    4:     = link_to vendor_path(@vendor), class: 'home' do
    5:       %i.fa.fa-home
  app/views/vendors/_menu.haml:2:in `_app_views_vendors__menu_haml__2535218153765224401_70111489365600'
  app/views/layouts/portal.haml:35:in `_app_views_layouts_portal_haml__3700871400531794207_70111685449560'
```
Any ideas if I should fix my code (tried couple of attempts, unsuccessful), or if it's a hamlit issue?

**Comment by k0kubun** [comment]
I'm sorry to take your time. :bow: 

It seems strange. I couldn't find code which can't be compiled by Hamlit. And these 5 lines do not have plain text. Is it possible to have some special character in 2nd line of _menu.haml?

I want to reproduce your problem and solve it. Could you provide some minimum files to reproduce your problem?

**Comment by gmile** [comment]
No worries @k0kubun, you're not taking my time!

I will prepare an example for you...

**Comment by Silex** [comment]
I have the same problem with the following code:

``` haml
%li.folder[downloader]
  .title
    Downloader
```

If I remove the `[downloader]` haml reference then it works fine.

**Comment by k0kubun** [comment]
The code @Silex wrote is the object reference feature, which is referenced in https://github.com/k0kubun/hamlit/issues/39. I'll support it later.

**Comment by Silex** [comment]
@k0kubun: alright, I'll monitor #39 then. Thanks.

**Comment by k0kubun** [comment]
Replaced parser with official one and supported object reference in https://github.com/k0kubun/hamlit/pull/43.

**Comment by gmile** [comment]
@k0kubun with 2.0 I'm seeing this same issue:

```
ActionView::Template::Error (Illegal nesting: nesting within plain text is illegal.):
    1: %ul.nav.nav-list
    2:   %li
    3:     %i.fa.fa-home
    4:     Home
  app/views/vendors/_menu.haml:2:in `_app_views_vendors__menu_haml___1815664066684057195_70255604612420'
  app/views/layouts/portal.haml:35:in `_app_views_layouts_portal_haml__3734192787514525598_70255594174600'
```

The above code actually is the entire template, e.g. there's nothing else, but this:

```haml
%ul.nav.nav-list
  %li
    %i.fa.fa-home
    Home
```

I tried parsing/compiling it with `haml` cli, and it didn't raise any error for me. Yet `ActionView::Template::Error` is somehow raised when using with rails (we are using Rails 4.2.0).

Effectively this prevents us from moving onto `hamlit` fully. Any ideas how to debug this?

**Comment by k0kubun** [comment]
Ummmmm.. it looks strange. The template can be compiled by hamlit v2.0.1 like:

```html
$ cat in.haml
%ul.nav.nav-list
  %li
    %i.fa.fa-home
    Home

$ bundle exec hamlit render in.haml
<ul class='nav nav-list'>
<li>
<i class='fa fa-home'></i>
Home
</li>
</ul>
```

Could you try:

- using Hamlit CLI in your Rails app directory and providing full backtrace
- restarting `rails s`
- making sure that `gem 'hamlit', '2.0.1'` is specified in Gemfile and starting rails by `bundle exec rails s`
- executing `spring stop`

**Comment by k0kubun** [comment]
> I tried parsing/compiling it with haml cli, and it didn't raise any error for me.

Ah, you mean `hamlit` cli?

**Comment by gmile** [comment]
@k0kubun yes, I meant `hamlit` cli. I get perfect results when parsing/compiling just like you did. But in conjunction with rails the template somehow fails.

**Comment by k0kubun** [comment]
I'll try debugging if you can provide reproductive repository.

If you can't provide it and you do it yourself, could you try deleting some lines in the template and provide some patterns which can be rendered and not?

**Comment by gmile** [comment]
@k0kubun I just tried from scratch repo, and it works just fine. It seems like the issue is somewhere in our rails app. I'll have to dig further.

Thanks for the support!

**Comment by k0kubun** [comment]
I hope you'll solve the problem :+1:
