### ISSUE TITLE
Case statement does'nt work

### ISSUE THREAD

**Issue by Prizrack13** [k0kubun/hamlit#41]
I saw that you have few tests that tests case statement. But it doen't give you full coverage.

```ruby
- test = 1
= case test
  - when 1 then 1
  - when 2 then 2
  - else 0
```
It raise error 
"syntax error, unexpected keyword_ensure, expecting end-of-input"

Than I understand that your case syntax little bit different.
```ruby
- test = 1
= case test
- when 1 then 1
- when 2 then 2
- else 0
```
But it still raise error
"syntax error, unexpected ')', expecting keyword_when  ...Utils.escape_html_safe((case 1))).to_s)); "
So final code that works
```ruby
- test = 1
- case test
- when 1
  1
- when 2 
  2
- else 0
```
or we can rewrite it to 
```ruby
- test = 1
- if test == 1
  1
- elsif test == 2
  2
- else 0
```
But It doesn't looks good for me. And I doesn't like that there is difference in syntax between haml and hamlit.

**Comment by k0kubun** [comment]
Thank you for reporting an issue. I'll fix it.

**Comment by k0kubun** [comment]
I replaced parser with official one and resolved this in https://github.com/k0kubun/hamlit/pull/43.
