### ISSUE TITLE
Hamlit doesn't recognize windows style line endings

### ISSUE THREAD

**Issue by konung** [k0kubun/hamlit#42]
Here is my error:

````ruby
Illegal nesting: content can't be both given on the same line as %html and nested within it.

	
!!!
%html{lang: 'en'}
  = render 'head'
  %body.sidebar-mini.skin-black-light.sidebar-collapse{class: "#{ controller.controller_name }" }
    .wrapper
      = render 'header'

````

Same code works just fine with haml.

I found the culprit - I develop on a windows machine ( using Sublime Text), and debian VM in a vagrant setup - to run my app. I have to use windows for dev - as I I need to use a bunch of windows apps for other stuff for my work. My production env is all Debian.  Anyways my git is setup to checkout as window sstyle line endings and commit as Unix style.  It was never an issue before - haml handles this just fine. 

One solution is to change all the files I guess. But I wanted to bring this to your and anyone else running to this attention - as this is not an obvious error. 

PS: On windows line end is usually CRLF ( Carrage Return LineFeed) , on unix it's just (LF)

**Comment by k0kubun** [comment]
Thank you for reporting an issue. I'll fix it.

**Comment by k0kubun** [comment]
This can be compiled by Hamlit v2.0.1 because it uses official Haml::Parser internally. Resolved by https://github.com/k0kubun/hamlit/pull/43.

**Comment by konung** [comment]
Thank you !
