### ISSUE TITLE
Hamlit 2.2.0 + Rails5Beta1 + Ruby 2.2 64bit

### ISSUE THREAD

**Issue by francesco-loreti** [k0kubun/hamlit#54]
I can't install this gem on Ruby 2.2 64bit(windows) with Rails 5 and Hamlit 2.2.0
The error on bunde install is:
----------------------------------------------------------------------------
Installing hamlit 2.2.0 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/hamlit-2.2.0/ext/hamlit
C:/Ruby22-64bit/bin/ruby.exe -r ./siteconf20160131-6508-1gturbz.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22-64bit/bin/$(RUBY_BASE_NAME)
C:/Ruby22-64bit/lib/ruby/2.2.0/fileutils.rb:357:in `symlink': symlink() function is unimplemented on this machine (NotImplementedError)
        from C:/Ruby22-64bit/lib/ruby/2.2.0/fileutils.rb:357:in `block in ln_s'
        from C:/Ruby22-64bit/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
        from C:/Ruby22-64bit/lib/ruby/2.2.0/fileutils.rb:355:in `ln_s'
        from extconf.rb:10:in `block in <main>'
        from extconf.rb:8:in `each'
        from extconf.rb:8:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22-64bit/lib/ruby/gems/2.2.0/gems/hamlit-2.2.0 for inspection.
Results logged to C:/Ruby22-64bit/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/hamlit-2.2.0/gem_make.out

Any solution?
Thanks!

**Comment by k0kubun** [comment]
Ah, the problem is Windows does not have symlink. I'll try to change the way to build in Windows.

**Comment by k0kubun** [comment]
@francesco-loreti I fixed Hamlit so that it can be built on windows in https://github.com/k0kubun/hamlit/pull/55.
It's released as Hamlit v2.2.1. Please try it.

**Comment by francesco-loreti** [comment]
Perfect!!! It's all ok :+1:

**Comment by k0kubun** [comment]
:smile:
