### ISSUE TITLE
The "plain" filter is escaped when it shouldn't be

### ISSUE THREAD

**Issue by shaneog** [k0kubun/hamlit#58]
I'm trying to use the [`:plain`](http://haml.info/docs/yardoc/file.REFERENCE.html#plain-filter) filter to output JSON-LD to a page.

Hamlit 1.7.2 outputs correctly but **v2.0.1+** escapes the quotes. According to the haml spec this shouldn't happen. If I want to escape the script code I would use the [`:escaped`](http://haml.info/docs/yardoc/file.REFERENCE.html#escaped-filter) filter.

Is this a bug or is there something else I should be doing?

_Example:_
```haml
%script{ type: 'application/ld+json' }
  :plain
    {
      "@context": "http://schema.org",
      "@type": "WebSite",
      "name": "My Website",
      "url": "#{root_url}"
    }
```
is output as:
```html
<script type='application/ld+json'>
{
  &quot;@context&quot;: &quot;http://schema.org&quot;,
  &quot;@type&quot;: &quot;WebSite&quot;,
  &quot;name&quot;: &quot;My Website&quot;,
  &quot;url&quot;: &quot;http://example.com/&quot;
}
</script>
```

**Comment by k0kubun** [comment]
Thank you for reporting an issue! It was a bug.

I fixed it in https://github.com/k0kubun/hamlit/commit/a0090c46892e71293b84e8a22a2e16b97f19170c and released the fixed version as v2.2.2.
