### ISSUE TITLE
`each` doesn't render

### ISSUE THREAD

**Issue by timoschilling** [k0kubun/hamlit#62]
Context:
I use a hand build render way:
```ruby
file = "foo.haml"
engine = Tilt[file] # => Hamlit::Template
template = engine.new(file, escape_html: false, escape_attrs: false)
template.render
```
Template:
```haml
%ul
  - (1..3).each do |i|
    %li
```
Result:
```html
<ul></ul>
```

**Comment by timoschilling** [comment]
Some debugging informations:
Based on the pervious code the compiled template source is:
```ruby
_buf = []; _buf << ("<ul>\n".freeze);
;  (1..3).each do |i|; 
; _hamlit_compiler1 = ''; _hamlit_compiler1 << ("<li>".freeze); _hamlit_compiler2 = (i;
; ); _hamlit_compiler1 << ((_hamlit_compiler2).to_s); _hamlit_compiler1 << ("</li>\n".freeze); _hamlit_compiler1; end; _buf << ("</ul>\n".freeze); _buf = _buf.join
```
The same template rendered with the hamlit comandline tool results in:
`bundle exec hamlit compile file.haml`
```ruby
_buf = []; _buf << ("<ul>\n".freeze);
;  (1..3).each do |i|;
; _buf << ("<li>".freeze); _hamlit_compiler1 = (i;
; ); _buf << (::Hamlit::Utils.escape_html((_hamlit_compiler1))); _buf << ("</li>\n".freeze); end; _buf << ("</ul>\n".freeze); _buf = _buf.join
```
`bundle exec hamlit render file.haml` brings the expected result:
```html
<ul>
<li>1</li>
<li>2</li>
<li>3</li>
</ul>
```
What am I doing wrong?

**Comment by timoschilling** [comment]
Both cases use hamlit `2.2.2`

**Comment by k0kubun** [comment]
Are you using hamlit-block?

**Comment by k0kubun** [comment]
See https://github.com/k0kubun/hamlit/issues/53#issuecomment-170331999, https://github.com/k0kubun/hamlit/issues/53#issuecomment-170334043 and https://github.com/k0kubun/hamlit/issues/53#issuecomment-170524664 for detail.
This is not a bug within Hamlit but a feature of hamlit-block.

**Comment by timoschilling** [comment]
Yes, I use `hamlit-block`. I'm the guy way nick has written #53. ;)

**Comment by timoschilling** [comment]
I close this as double of hamlit/hamlit-block#1
