### ISSUE TITLE
remove_filter?

### ISSUE THREAD

**Issue by connorshea** [k0kubun/hamlit#66]
HAML has a [`remove_filter`](https://github.com/haml/haml/blob/025b89f421a31cd18db5cacdbcf69cbec893322f/lib/haml/filters.rb#L67) method. I noticed there's a test for Hamlit's remove_filter method [here](https://github.com/k0kubun/hamlit/blob/master/test/haml/filters_test.rb#L10). but I can't get it to work when adding the following to `hamlit.rb`:

```ruby
Hamlit::Filters.remove_filter "Coffee"
```

This is the error I get: ```undefined method 'remove_filter' for Hamlit::Filters:Class (NoMethodError)```

Any ideas?

**Comment by k0kubun** [comment]
Implemented `Hamlit::Filters.remove_filter` and released in Hamlit v2.3.0.

**Comment by connorshea** [comment]
👍 thanks!
