### ISSUE TITLE
If the first line of the file is evaluated Ruby, the line doesn't evaluate.

### ISSUE THREAD

**Issue by bdcheung** [k0kubun/hamlit#68]
# sample.haml
    -foo = "bar"
    =foo

raises `undefined local variable or method `foo' `, but

    # sample.haml
    
    -foo = "bar"
    =foo

evaluates as expected.

Without that blank first line, the first line of evaluated ruby doesn't get evaluated.

**Comment by k0kubun** [comment]
It wasn't reproductive on my environment. I confirmed it with CLI in a following way and with a dummy rails app.

```ruby
$ cat in.haml
-foo = "bar"
=foo
$ hamlit render in.haml
bar
```

I want to solve the problem. Could you provide more information to reproduce the bug?
At least I want to know:

- Ruby version
- Hamlit version

https://github.com/k0kubun/hamlit#reporting-an-issue

Sample repository or detail reproductive steps would be appreciated.

**Comment by bdcheung** [comment]
I'll work on getting a gist up--the issue is in a private repo and, oddly, appears to be only happening with a specific partial.

I'll also see if I can find a set of conditions for reproducing the issue.

**Comment by bdcheung** [comment]
Found the issue.

There was a hidden <U+FEFF> unicode character (zero with no-break space) at the beginning of the file that I couldn't see in either vim or any IDE.  Removing that resulted in the partial being rendered as expected.

**Comment by k0kubun** [comment]
Wow, it'd be hard to find. Thank you for the investigation and sharing!

**Comment by bdcheung** [comment]
I only found it by copying and pasting the contents of the broken partial into a new file, overwriting the original, and running a `git diff`.

**Comment by mbrand12** [comment]
Talk about hard to find issue. Kinda reminds me of this oddity https://twitter.com/benbjohnson/status/533848879423578112?lang=en
