### ISSUE TITLE
[2.4.0] Symlink error on Windows x64

### ISSUE THREAD

**Issue by francesco-loreti** [k0kubun/hamlit#69]
current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hamlit-2.4.0/ext/hamlit
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20160603-6444-1o9hsk7.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/Ruby23-x64/bin/$(RUBY_BASE_NAME)
C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:358:in `symlink': Permission denied @ rb_file_s_symlink - (C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hamlit-2.4.0/ext/hamlit/houdini/buffer.c, buffer.c) (Errno::EACCES)
	from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:358:in `block in ln_s'
	from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
	from C:/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:356:in `ln_s'
	from extconf.rb:11:in `block in <main>'
	from extconf.rb:8:in `each'
	from extconf.rb:8:in `<main>'

extconf failed, exit code 1

**Comment by k0kubun** [comment]
Can you install Hamlit 2.2.1 in the same environment now? I think Hamlit 2.4.0 can be installed if you can install Hamlit 2.2.1 like https://github.com/k0kubun/hamlit/issues/54.

**Comment by francesco-loreti** [comment]
No I can't install Hamlit 2.2.1. I have same error with symlink.

**Comment by k0kubun** [comment]
It seems that you use Ruby 2.3.0 now. Can you install Hamlit v2.2.1 with Ruby 2.2.0?

And if you install Ruby with privileged user, could you try chaning the owner of `C:/Ruby23-x64/` to the user you're using recursively? It'll be installed when you have write permission to `C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/hamlit-2.4.0/ext/hamlit/`.

**Comment by francesco-loreti** [comment]
Yes with Ruby 2.2.4p230 x64 I can install Hamlit v2.2.1 and v2.4.0 but I have same authorizations on Ruby22-x64 and Ruby23-x64.

**Comment by k0kubun** [comment]
Got it. Could you try Hamlit v2.4.1?

**Comment by francesco-loreti** [comment]
New error:
current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/hamlit-74a1e1be46b2/ext/hamlit
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20160603-2268-1xckd14.rb extconf.rb
creating Makefile

current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/hamlit-74a1e1be46b2/ext/hamlit
make "DESTDIR=" clean

current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/hamlit-74a1e1be46b2/ext/hamlit
make "DESTDIR="
generating hamlit-x64-mingw32.def
compiling hamlit.c
hamlit.c:3:21: fatal error: houdini.h: No such file or directory
compilation terminated.
make: *** [hamlit.o] Error 1

make failed, exit code 2

**Comment by k0kubun** [comment]
Difficult...

I want to check four things.

1. The content of `C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/hamlit-74a1e1be46b2/ext/hamlit/Makefile`
2. The content of `C:/Ruby23-x64/lib/ruby/gems/2.2.0/bundler/gems/hamlit-74a1e1be46b2/ext/hamlit/Makefile`
3.  The list of files inside `C:/Ruby23-x64/lib/ruby/gems/2.2.0/bundler/gems/hamlit-74a1e1be46b2/ext/hamlit/houdini`
4. The full log of `bundle exec rake compile` in Hamlit repository in Ruby 2.2. and 2.3. If it's hard, `gem install hamlit` is ok.

**Comment by francesco-loreti** [comment]
Ok I prepare the tests...
But I have a strange error:
1. gem install hamlit -v '2.4.1'
2. ERROR:  Could not find a valid gem 'hamlit' (= 2.4.1) in any repository

**Comment by k0kubun** [comment]
I confirmed the same problem now but no workaround was found...
Anyway, could you test `rake compile` from the source repository?

**Comment by francesco-loreti** [comment]
> bundle exec rake compile
mkdir -p tmp/x64-mingw32/hamlit/2.3.0
cd tmp/x64-mingw32/hamlit/2.3.0
C:/Ruby23-x64/bin/ruby.exe -I. ../../../../ext/hamlit/extconf.rb
creating Makefile
cd -
cd tmp/x64-mingw32/hamlit/2.3.0
c:\DevKit-x64\bin/make.exe
generating hamlit-x64-mingw32.def
compiling ../../../../ext/hamlit/hamlit.c
../../../../ext/hamlit/hamlit.c:3:21: fatal error: houdini.h: No such file or directory
compilation terminated.
make: *** [hamlit.o] Error 1
rake aborted!
Command failed with status (2): [c:\DevKit-x64\bin/make.exe...]

Tasks: TOP => compile => compile:x64-mingw32 => compile:hamlit:x64-mingw32 => copy:hamlit:x64-mingw32:2.3.0 => tmp/x64-mingw32/hamlit/2.3.0/hamlit.so
(See full trace by running task with --trace)

**Comment by k0kubun** [comment]
Thanks.

I want to see the content of Makefile, which is in tmp/x64-mingw32/hamlit/2.3.0/.

**Comment by francesco-loreti** [comment]
SHELL = /bin/sh

# V=0 quiet, V=1 verbose.  other values don't work.
V = 0
Q1 = $(V:1=)
Q = $(Q1:0=@)
ECHO1 = $(V:1=@:)
ECHO = $(ECHO1:0=@echo)
NULLCMD = :

#### Start of system configuration section. ####

srcdir = ../../../../ext/hamlit
topdir = /C/Ruby23-x64/include/ruby-2.3.0
hdrdir = $(topdir)
arch_hdrdir = C:/Ruby23-x64/include/ruby-2.3.0/x64-mingw32
PATH_SEPARATOR = :
VPATH = $(srcdir):$(arch_hdrdir)/ruby:$(hdrdir)/ruby
prefix = $(DESTDIR)/C/Ruby23-x64
rubysitearchprefix = $(rubylibprefix)/$(sitearch)
rubyarchprefix = $(rubylibprefix)/$(arch)
rubylibprefix = $(libdir)/$(RUBY_BASE_NAME)
exec_prefix = $(prefix)
vendorarchhdrdir = $(vendorhdrdir)/$(sitearch)
sitearchhdrdir = $(sitehdrdir)/$(sitearch)
rubyarchhdrdir = $(rubyhdrdir)/$(arch)
vendorhdrdir = $(rubyhdrdir)/vendor_ruby
sitehdrdir = $(rubyhdrdir)/site_ruby
rubyhdrdir = $(includedir)/$(RUBY_VERSION_NAME)
vendorarchdir = $(vendorlibdir)/$(sitearch)
vendorlibdir = $(vendordir)/$(ruby_version)
vendordir = $(rubylibprefix)/vendor_ruby
sitearchdir = $(sitelibdir)/$(sitearch)
sitelibdir = $(sitedir)/$(ruby_version)
sitedir = $(rubylibprefix)/site_ruby
rubyarchdir = $(rubylibdir)/$(arch)
rubylibdir = $(rubylibprefix)/$(ruby_version)
sitearchincludedir = $(includedir)/$(sitearch)
archincludedir = $(includedir)/$(arch)
sitearchlibdir = $(libdir)/$(sitearch)
archlibdir = $(libdir)/$(arch)
ridir = $(datarootdir)/$(RI_BASE_NAME)
mandir = $(datarootdir)/man
localedir = $(datarootdir)/locale
libdir = $(exec_prefix)/lib
psdir = $(docdir)
pdfdir = $(docdir)
dvidir = $(docdir)
htmldir = $(docdir)
infodir = $(datarootdir)/info
docdir = $(datarootdir)/doc/$(PACKAGE)
oldincludedir = $(DESTDIR)/usr/include
includedir = $(prefix)/include
localstatedir = $(prefix)/var
sharedstatedir = $(prefix)/com
sysconfdir = $(prefix)/etc
datadir = $(datarootdir)
datarootdir = $(prefix)/share
libexecdir = $(exec_prefix)/libexec
sbindir = $(exec_prefix)/sbin
bindir = $(exec_prefix)/bin
archdir = $(rubyarchdir)


CC = x86_64-w64-mingw32-gcc
CXX = x86_64-w64-mingw32-g++
LIBRUBY = lib$(RUBY_SO_NAME).dll.a
LIBRUBY_A = lib$(RUBY_SO_NAME)-static.a
LIBRUBYARG_SHARED = -l$(RUBY_SO_NAME)
LIBRUBYARG_STATIC = -l$(RUBY_SO_NAME)-static
empty =
OUTFLAG = -o $(empty)
COUTFLAG = -o $(empty)

RUBY_EXTCONF_H = 
cflags   =  $(optflags) $(debugflags) $(warnflags)
cxxflags =  $(optflags) $(debugflags) $(warnflags)
optflags = -O3 -fno-omit-frame-pointer -fno-fast-math
debugflags = -g
warnflags = -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat
CCDLFLAGS = 
CFLAGS   = $(CCDLFLAGS) $(cflags) -Wall -Wextra $(ARCH_FLAG)
INCFLAGS = -I. -I$(arch_hdrdir) -I$(hdrdir)/ruby/backward -I$(hdrdir) -I$(srcdir) -ID:/sviluppo/rails/hamlit/ext/hamlit/houdini
DEFS     = -D_FILE_OFFSET_BITS=64
CPPFLAGS =  -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT $(DEFS) $(cppflags)
CXXFLAGS = $(CCDLFLAGS) $(cxxflags) $(ARCH_FLAG)
ldflags  = -L. 
dldflags =  -Wl,--enable-auto-image-base,--enable-auto-import $(DEFFILE) 
ARCH_FLAG = 
DLDFLAGS = $(ldflags) $(dldflags) $(ARCH_FLAG)
LDSHARED = $(CC) -shared $(if $(filter-out -g -g0,$(debugflags)),,-s)
LDSHAREDXX = $(CXX) -shared $(if $(filter-out -g -g0,$(debugflags)),,-s)
AR = ar
EXEEXT = .exe

RUBY_INSTALL_NAME = $(RUBY_BASE_NAME)
RUBY_SO_NAME = x64-msvcrt-ruby230
RUBYW_INSTALL_NAME = $(RUBYW_BASE_NAME)
RUBY_VERSION_NAME = $(RUBY_BASE_NAME)-$(ruby_version)
RUBYW_BASE_NAME = rubyw
RUBY_BASE_NAME = ruby

arch = x64-mingw32
sitearch = x64-msvcrt
ruby_version = 2.3.0
ruby = $(bindir)/$(RUBY_BASE_NAME)
RUBY = $(ruby)
ruby_headers = $(hdrdir)/ruby.h $(hdrdir)/ruby/ruby.h $(hdrdir)/ruby/defines.h $(hdrdir)/ruby/missing.h $(hdrdir)/ruby/intern.h $(hdrdir)/ruby/st.h $(hdrdir)/ruby/subst.h $(arch_hdrdir)/ruby/config.h

RM = rm -f
RM_RF = $(RUBY) -run -e rm -- -rf
RMDIRS = rmdir --ignore-fail-on-non-empty -p
MAKEDIRS = /usr/bin/mkdir -p
INSTALL = /usr/bin/install -c
INSTALL_PROG = $(INSTALL) -m 0755
INSTALL_DATA = $(INSTALL) -m 644
COPY = cp
TOUCH = exit >

#### End of system configuration section. ####

preload = 

libpath = . $(libdir)
LIBPATH =  -L. -L$(libdir)
DEFFILE = $(TARGET)-$(arch).def

CLEANFILES = mkmf.log $(DEFFILE)
DISTCLEANFILES = 
DISTCLEANDIRS = 

extout = 
extout_prefix = 
target_prefix = /hamlit
LOCAL_LIBS = 
LIBS = $(LIBRUBYARG_SHARED)  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  
ORIG_SRCS = hamlit.c
SRCS = $(ORIG_SRCS) hamlit.c
OBJS = hamlit.o
HDRS = 
TARGET = hamlit
TARGET_NAME = hamlit
TARGET_ENTRY = Init_$(TARGET_NAME)
DLLIB = $(TARGET).so
EXTSTATIC = 
STATIC_LIB = 

TIMESTAMP_DIR = .
BINDIR        = $(bindir)
RUBYCOMMONDIR = $(sitedir)$(target_prefix)
RUBYLIBDIR    = $(sitelibdir)$(target_prefix)
RUBYARCHDIR   = $(sitearchdir)$(target_prefix)
HDRDIR        = $(rubyhdrdir)/ruby$(target_prefix)
ARCHHDRDIR    = $(rubyhdrdir)/$(arch)/ruby$(target_prefix)

TARGET_SO     = $(DLLIB)
CLEANLIBS     = $(TARGET).so 
CLEANOBJS     = *.o  *.bak

all:    $(DLLIB)
static: $(STATIC_LIB) install-rb
.PHONY: all install static install-so install-rb
.PHONY: clean clean-so clean-static clean-rb

clean-static::
clean-rb-default::
clean-rb::
clean-so::
clean: clean-so clean-static clean-rb-default clean-rb
		-$(Q)$(RM) $(CLEANLIBS) $(CLEANOBJS) $(CLEANFILES) .*.time

distclean-rb-default::
distclean-rb::
distclean-so::
distclean-static::
distclean: clean distclean-so distclean-static distclean-rb-default distclean-rb
		-$(Q)$(RM) Makefile $(RUBY_EXTCONF_H) conftest.* mkmf.log
		-$(Q)$(RM) core ruby$(EXEEXT) *~ $(DISTCLEANFILES)
		-$(Q)$(RMDIRS) $(DISTCLEANDIRS) 2> /dev/null || true

realclean: distclean
install: install-so install-rb

install-so: $(DLLIB) $(TIMESTAMP_DIR)/.RUBYARCHDIR.-.hamlit.time
	$(INSTALL_PROG) $(DLLIB) $(RUBYARCHDIR)
clean-static::
	-$(Q)$(RM) $(STATIC_LIB)
install-rb: pre-install-rb install-rb-default
install-rb-default: pre-install-rb-default
pre-install-rb: Makefile
pre-install-rb-default: Makefile
pre-install-rb-default:
	@$(NULLCMD)
$(TIMESTAMP_DIR)/.RUBYARCHDIR.-.hamlit.time:
	$(Q) $(MAKEDIRS) $(@D) $(RUBYARCHDIR)
	$(Q) $(TOUCH) $@

site-install: site-install-so site-install-rb
site-install-so: install-so
site-install-rb: install-rb

.SUFFIXES: .c .m .cc .mm .cxx .cpp .o .S

.cc.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cc.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.mm.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.mm.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.cxx.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cxx.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.cpp.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cpp.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.c.o:
	$(ECHO) compiling $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -c $<

.c.S:
	$(ECHO) translating $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -S $<

.m.o:
	$(ECHO) compiling $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -c $<

.m.S:
	$(ECHO) translating $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -S $<

$(DLLIB): $(DEFFILE) $(OBJS) Makefile
	$(ECHO) linking shared-object hamlit/$(DLLIB)
	-$(Q)$(RM) $(@)
	$(Q) $(LDSHARED) -o $@ $(OBJS) $(LIBPATH) $(DLDFLAGS) $(LOCAL_LIBS) $(LIBS)



$(DEFFILE): 
	$(ECHO) generating $(@)
	$(Q) (echo EXPORTS && echo $(TARGET_ENTRY)) > $@

$(OBJS): $(HDRS) $(ruby_headers)

**Comment by k0kubun** [comment]
```
INCFLAGS = -I. -I$(arch_hdrdir) -I$(hdrdir)/ruby/backward -I$(hdrdir) -I$(srcdir) -ID:/sviluppo/rails/hamlit/ext/hamlit/houdini
```

So houdini.h will be searched from `D:/sviluppo/rails/hamlit/ext/hamlit/houdini`. Could you show the list of files in `D:/sviluppo/rails/hamlit/ext/hamlit/houdini`?

(I'm wondering why it's in D drive different from C drive in which Ruby exists.)

**Comment by francesco-loreti** [comment]
Oh I'm sorry I have cloned the gem, for compile it, in D:\ but I have C:\Ruby23-x64\bin into "enviroments path" so it's not a problem...
But If you want I can put the folder into another path... explain me where...

**Comment by k0kubun** [comment]
The drive is ok for now. I want to know the files in `D:/sviluppo/rails/hamlit/ext/hamlit/houdini`.
And please make sure that houdini is cloned in ext/hamlit/houdini. `git clone --recursive` or `git submodule init && git submodule update` is required.

**Comment by francesco-loreti** [comment]
Ok... I have executed "git submodule init && git submodule update" and I have this error:

cd tmp/x64-mingw32/hamlit/2.3.0
c:\DevKit-x64\bin/make.exe
compiling ../../../../ext/hamlit/hamlit.c
linking shared-object hamlit/hamlit.so
hamlit.o: In function `escape_html':
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:61: undefined reference to `gh_buf__initbuf'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:65: undefined reference to `houdini_escape_html0'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:67: undefined reference to `gh_buf_free'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:61: undefined reference to `gh_buf__initbuf'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:65: undefined reference to `houdini_escape_html0'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:67: undefined reference to `gh_buf_free'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:61: undefined reference to `gh_buf__initbuf'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:65: undefined reference to `houdini_escape_html0'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:67: undefined reference to `gh_buf_free'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:61: undefined reference to `gh_buf__initbuf'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:65: undefined reference to `houdini_escape_html0'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:67: undefined reference to `gh_buf_free'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:61: undefined reference to `gh_buf__initbuf'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:65: undefined reference to `houdini_escape_html0'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:67: undefined reference to `gh_buf_free'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:61: undefined reference to `gh_buf__initbuf'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:65: undefined reference to `houdini_escape_html0'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:67: undefined reference to `gh_buf_free'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:61: undefined reference to `gh_buf__initbuf'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:65: undefined reference to `houdini_escape_html0'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:67: undefined reference to `gh_buf_free'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:61: undefined reference to `gh_buf__initbuf'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:65: undefined reference to `houdini_escape_html0'
d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0/../../../../ext/hamlit/hamlit.c:67: undefined reference to `gh_buf_free'
collect2.exe: error: ld returned 1 exit status
make: *** [hamlit.so] Error 1
rake aborted!
Command failed with status (2): [c:\DevKit-x64\bin/make.exe...]

Tasks: TOP => compile => compile:x64-mingw32 => compile:hamlit:x64-mingw32 => copy:hamlit:x64-mingw32:2.3.0 => tmp/x64-mingw32/hamlit/2.3.0/hamlit.so
(See full trace by running task with --trace)

**Comment by k0kubun** [comment]
Could you show the list of files in `D:/sviluppo/rails/hamlit/ext/hamlit/houdini`?

**Comment by k0kubun** [comment]
Now I want to see files in `D:/sviluppo/rails/hamlit/ext/hamlit/` too.

**Comment by k0kubun** [comment]
Sorry for commenting many times but could you show the files in `d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0`?

**Comment by francesco-loreti** [comment]
ok ok I have compiled hamlit.so into d:\sviluppo\rails\hamlit\tmp\x64-mingw32\hamlit\2.3.0

**Comment by k0kubun** [comment]
Only hamlit.so? In my case,

```
~/src/.../hamlit/2.3.1 $ pwd                                                                                                      (git)-[master]-
/home/k0kubun/src/github.com/k0kubun/hamlit/tmp/x86_64-linux/hamlit/2.3.1
~/src/.../hamlit/2.3.1 $ ls                                                                                                       (git)-[master]-
合計 1580
drwxr-xr-x 1 k0kubun wheel    566  6月  4 00:15 .
drwxr-xr-x 1 k0kubun wheel     10  6月  4 00:15 ..
-rw-r--r-- 1 k0kubun wheel   7937  6月  4 00:15 Makefile
lrwxrwxrwx 1 k0kubun wheel     71  6月  4 00:15 buffer.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/buffer.c
-rw-r--r-- 1 k0kubun wheel 138024  6月  4 00:15 buffer.o
-rw-r--r-- 1 k0kubun wheel 362432  6月  4 00:15 hamlit.o
-rwxr-xr-x 1 k0kubun wheel 312720  6月  4 00:15 hamlit.so
lrwxrwxrwx 1 k0kubun wheel     79  6月  4 00:15 houdini_href_e.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/houdini_href_e.c
-rw-r--r-- 1 k0kubun wheel  87944  6月  4 00:15 houdini_href_e.o
lrwxrwxrwx 1 k0kubun wheel     79  6月  4 00:15 houdini_html_e.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/houdini_html_e.c
-rw-r--r-- 1 k0kubun wheel  89472  6月  4 00:15 houdini_html_e.o
lrwxrwxrwx 1 k0kubun wheel     79  6月  4 00:15 houdini_html_u.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/houdini_html_u.c
-rw-r--r-- 1 k0kubun wheel 113704  6月  4 00:15 houdini_html_u.o
lrwxrwxrwx 1 k0kubun wheel     77  6月  4 00:15 houdini_js_e.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/houdini_js_e.c
-rw-r--r-- 1 k0kubun wheel  87848  6月  4 00:15 houdini_js_e.o
lrwxrwxrwx 1 k0kubun wheel     77  6月  4 00:15 houdini_js_u.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/houdini_js_u.c
-rw-r--r-- 1 k0kubun wheel  87296  6月  4 00:15 houdini_js_u.o
lrwxrwxrwx 1 k0kubun wheel     78  6月  4 00:15 houdini_uri_e.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/houdini_uri_e.c
-rw-r--r-- 1 k0kubun wheel  92440  6月  4 00:15 houdini_uri_e.o
lrwxrwxrwx 1 k0kubun wheel     78  6月  4 00:15 houdini_uri_u.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/houdini_uri_u.c
-rw-r--r-- 1 k0kubun wheel  89920  6月  4 00:15 houdini_uri_u.o
lrwxrwxrwx 1 k0kubun wheel     78  6月  4 00:15 houdini_xml_e.c -> /home/k0kubun/src/github.com/k0kubun/hamlit/ext/hamlit/houdini/houdini_xml_e.c
-rw-r--r-- 1 k0kubun wheel  90744  6月  4 00:15 houdini_xml_e.o
```

`houdini_html_e.c` has to exist in that directory. The undefined reference of `houdini_escape_html0` was define in that file.

And please try `rake clobber` before `rake compile`.

**Comment by francesco-loreti** [comment]
buffer.c
buffer.o
hamlit-x64-mingw32.def
hamlit.o
hamlit.so
houdini_href_e.c
houdini_href_e.o
houdini_html_e.c
houdini_html_e.o
houdini_html_u.c
houdini_html_u.o
houdini_js_e.c
houdini_js_e.o
houdini_js_u.c
houdini_js_u.o
houdini_uri_e.c
houdini_uri_e.o
houdini_uri_u.c
houdini_uri_u.o
houdini_xml_e.c
houdini_xml_e.o
Makefile

**Comment by k0kubun** [comment]
Looks good, but

```
SRCS = $(ORIG_SRCS) hamlit.c
```

Makefile was wrong.

Again, please try `rake clobber` before `rake compile`. If that fails, try `git clone --recursive` in anywhere again.

**Comment by francesco-loreti** [comment]
rake clobber --> ok
rake compile --> ok

No errors :+1:

**Comment by k0kubun** [comment]
Ruby 2.3 and your environment are capable of compiling latest Hamlit.

I released Hamlit v2.4.2 with a trivial fix which may not affect you but it allows me to execute `gem install hamlit -v 2.4.2`. Could you try it again?

**Comment by francesco-loreti** [comment]
Now It's OK!!! :+1:

**Comment by k0kubun** [comment]
Great. Thank you for your help!
