### ISSUE TITLE
config/initializers/hamlit.rb

### ISSUE THREAD

**Issue by WaKeMaTTa** [k0kubun/hamlit#70]
I can do this :question: 

```ruby
# config/initializers/hamlit.rb
Hamlit::Template.options[:format] = :html5
```

**Comment by k0kubun** [comment]
`Hamlit::Template` is not used for Rails since it's used for Tilt and not registered as ActionView handler.
`Hamlit::RailsTemplate` is the one and you can do `Hamlit::RailsTemplate.set_options format: :html5`.

https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md#set-options-for-rails

**Comment by k0kubun** [comment]
In addition, Hamlit does not distinguish `:html4` with `:html5` because Temple, which is a framework that Slim also uses, drops `:html4` option and `:html` in Hamlit means `:html5` of Haml.
So the setting is unnecessary.

**Comment by WaKeMaTTa** [comment]
Roger that. Thanks :+1:
