### ISSUE TITLE
Documentation for non Rails/Sinatrna users and Tilt bindings

### ISSUE THREAD

**Issue by dux** [k0kubun/hamlit#72]
It would be nice to have clean reference for native usage with all possible render options. Also bindings for Tilt would come useful.

**Comment by dux** [comment]
ok, for Tilt

instead
Tilt.register Tilt::HamlTemplate, 'haml'

we have to use
Tilt.register Hamlit::Template, 'haml'

and all works great.

**Comment by k0kubun** [comment]
> It would be nice to have clean reference for native usage with all possible render options

What do you mean with "render options"? Do you want https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md#engine-options?

> Also bindings for Tilt would come useful.
> we have to use
> Tilt.register Hamlit::Template, 'haml'

Exactly. `Hamlit::Template` is the binding for Tilt. Note that https://github.com/k0kubun/hamlit/blob/v2.5.0/lib/hamlit/template.rb#L6-L17 achieves the same overriding in https://github.com/judofyr/temple/blob/v0.7.7/lib/temple/templates/tilt.rb#L41-L43 and you don't have to explicitly do that.
