### ISSUE TITLE
Unable to render a partial

### ISSUE THREAD

**Issue by snowmac** [k0kubun/hamlit#78]
So I need to render a parital and the code I use to generate the HTML when it's the Haml engine is: 

    Haml::Engine.new(partial).render(self, options)

What would be the code for Hamlit?

**Comment by k0kubun** [comment]
Id'be based on what kind of things you're passing by `partial`, `self` and `options`. Probably you want `Hamlit::Template`.

```rb
[1] pry(main)> partial = "%a\n = b + c"
=> "%a\n = b + c"
[2] pry(main)> def b
[2] pry(main)*   'hello '
[2] pry(main)* end
=> :b
[3] pry(main)> Haml::Engine.new(partial).render(self, c: 'world')
=> "<a>\n  hello world\n</a>\n"
[4] pry(main)> Hamlit::Template.new { partial }.render(self, c: 'world')
=> "<a>\nhello world\n</a>\n"
```

**Comment by snowmac** [comment]
Thank you. Doing that as a template renders it as a html string, but when I render it to the browser, its a string of html not the ui view. How do I fix that?

**Comment by k0kubun** [comment]
I couldn't understand what you want to do. What do you want to do? If you're building web app, what framework do you use? 

See https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md for Rails or Sinatra.
Otherwise, you should use Tilt interface.

**Comment by k0kubun** [comment]
> when I render it to the browser, its a string of html not the ui view

I guess there're two possibilities.

1. Some parts of elements you want to render are HTML-escaped
  - One of biggest difference between Haml and Hamlit is that Hamlit HTML-escapes Ruby scripts.
  - Try `Hamlit::Template.new(escape_html: false) { partial }.render(self, {})`
2. Don't you set a response header "Content-Type: text/html;"?
  - It's not related to Hamlit, though.

**Comment by k0kubun** [comment]
Closing for now. Feel free to reopen this issue if you still have a problem.
