### ISSUE TITLE
TAB indent incompatible with haml

### ISSUE THREAD

**Issue by tdtds** [k0kubun/hamlit#9]
# Haml
```ruby
require 'haml'
Haml::Engine.new("%p\n\t%a").to_html()
=>  "<p>\n  <a></a>\n</p>\n"
```

# Hamlit
```ruby
require 'hamlit'
eval Hamlit::Engine.new.call("%p\n\t%a")
=> "<p></p>\n%a\n"
```

**Comment by k0kubun** [comment]
I changed hamlit to be compatible with haml's ugly mode about tab indentation. (currently pretty mode is not supported)
Thank you for your testing :smiley:

**Comment by tdtds** [comment]
sure, I'm an ugly programmer! thanks.
