### ISSUE TITLE
stdout filled with "Hamlit::Engine: Option :buffer_class is invalid" traces

### ISSUE THREAD

**Issue by kikonen** [k0kubun/hamlit#90]
After updating to hamlit 2.7.1, stdout is filled with "Hamlit::Engine: Option :buffer_class is invalid" traces.

ENV:
- rails (5.0.0.1)
- sprockets (3.6.3)

**Comment by francesco-loreti** [comment]
I have same error.
ENV:

    rails (5.0.0.1)
    sprockets (3.7.0)

**Comment by k0kubun** [comment]
Sorry for bothering you :bow:

I fixed it in https://github.com/k0kubun/hamlit/commit/b196cb239ad7cb27d739be8f2e15bcaac13a656c.
Could you try Hamlit v2.7.2?
