### ISSUE TITLE
Data attribute is not rendered if the value is false

### ISSUE THREAD

**Issue by jeffblake** [k0kubun/hamlit#93]
For example

`%input{data: {preload: false}}`

Results in 

`<input></input>`

I would expect that the data attribute is included, even if the value is false.

**Comment by k0kubun** [comment]
It's by design https://github.com/k0kubun/hamlit/blob/v2.7.5/REFERENCE.md#limited-boolean-attributes.
And compatible behavior with Haml.

```
~/tmp $ cat input.haml
%input{data: {preload: false}}
~/tmp $ haml -v
Haml 4.1.0.beta.1
~/tmp $ haml -e -t ugly input.haml
<input>
~/tmp $ hamlit version
2.7.2
~/tmp $ hamlit input.haml
<input>
```

**Comment by jeffblake** [comment]
Hmm ok. Thanks. I'll just add a symbol to `false` then.

**Comment by k0kubun** [comment]
Just curious, what's your use case? Why do you want to render attribute even if it's false?

**Comment by WaKeMaTTa** [comment]
This is correct, if yo want to ger thé value false u need to do it like this

    %input{data: {preload: 'false'}}
