### ISSUE TITLE
Failures when used in conjunction with html5-rails gem

### ISSUE THREAD

**Issue by contentfree** [k0kubun/hamlit#98]
The error is: 
```
undefined method `haml_concat' for #<#<Class:…>>
```

[The `html_tag` helper from html5-rails](https://github.com/sporkd/html5-rails/blob/master/lib/html5/rails/helpers.rb#L16) uses `haml_concat` which doesn't exist in Hamlit.

**Comment by k0kubun** [comment]
Basically the same issue as https://github.com/k0kubun/hamlit/issues/73. For some reasons, haml helpers are missing for now. 
https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md#limitations
